In [1]:
import blackjack as bj
import numpy as np

In [2]:
module = bj.Blackjack(t=np.array([3]*3+[6], dtype=np.uint8),
                      scores=np.arange(1,5),
                      b=10,
                      a=5,
                      q_init=1)

In [3]:
module.state_dict.keys()

dict_keys(['[0 0 0 0][0 0 0 0]0', '[0 0 0 0][1 0 0 0]0', '[1 0 0 0][1 0 0 0]0', '[2 0 0 0][1 0 0 0]0', '[2 1 0 0][1 0 0 0]0', '[2 2 0 0][1 0 0 0]0', '[2 3 0 0][1 0 0 0]0', '[2 3 1 0][1 0 0 0]0', '[2 3 0 1][1 0 0 0]0', '[2 3 0 0][1 0 0 0]1', '[2 3 0 0][1 0 1 0]1', '[2 3 0 0][1 0 2 0]1', '[2 3 0 0][1 0 3 0]1', '[2 3 0 0][1 0 2 1]1', '[2 3 0 0][1 0 1 1]1', '[2 3 0 0][1 0 0 1]1', '[2 3 0 0][1 0 0 2]1', '[2 3 0 0][1 0 1 2]1', '[2 3 0 0][1 0 0 3]1', '[2 2 1 0][1 0 0 0]0', '[2 2 2 0][1 0 0 0]0', '[2 2 1 1][1 0 0 0]0', '[2 2 1 0][1 0 0 0]1', '[2 2 1 0][1 1 0 0]1', '[2 2 1 0][1 1 1 0]1', '[2 2 1 0][1 1 2 0]1', '[2 2 1 0][1 1 1 1]1', '[2 2 1 0][1 1 0 1]1', '[2 2 1 0][1 0 1 0]1', '[2 2 1 0][1 0 2 0]1', '[2 2 1 0][1 0 1 1]1', '[2 2 1 0][1 0 0 1]1', '[2 2 1 0][1 0 0 2]1', '[2 2 0 1][1 0 0 0]0', '[2 2 0 2][1 0 0 0]0', '[2 2 0 1][1 0 0 0]1', '[2 2 0 1][1 1 0 0]1', '[2 2 0 1][1 1 1 0]1', '[2 2 0 1][1 1 2 0]1', '[2 2 0 1][1 1 3 0]1', '[2 2 0 1][1 1 2 1]1', '[2 2 0 1][1 1 1 1]1', '[2 2 0 1][1 1 0 1]1', 

In [4]:
np.unique([module.state_dict[key]['score_h'] for key in module.state_dict.keys()])

array([ 0.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [5]:
module.state_dict[module.get_dict_key(np.zeros_like(module.t),
                                      np.zeros_like(module.t),
                                      0)]

{'p': array([0.2, 0.2, 0.2, 0.4]),
 'h_plus': [array([1, 0, 0, 0], dtype=uint8),
  array([0, 1, 0, 0], dtype=uint8),
  array([0, 0, 1, 0], dtype=uint8),
  array([0, 0, 0, 1], dtype=uint8)],
 'd_plus': [array([1, 0, 0, 0], dtype=uint8),
  array([0, 1, 0, 0], dtype=uint8),
  array([0, 0, 1, 0], dtype=uint8),
  array([0, 0, 0, 1], dtype=uint8)],
 'score_h': 0,
 'score_d': 0,
 'score_bust_h': False,
 'score_bust_d': False,
 'win': 0,
 'num_cards_h': 0,
 'num_cards_d': 0,
 'num_residual_cards': 15}

In [6]:
module.state_dict[module.get_dict_key(np.array([0,0,0,3]),
                                      np.array([1,0,0,0]),
                                      0)]

{'p': array([0.18181818, 0.27272727, 0.27272727, 0.27272727]),
 'h_plus': [array([1, 0, 0, 3], dtype=uint8),
  array([0, 1, 0, 3], dtype=uint8),
  array([0, 0, 1, 3], dtype=uint8),
  array([0, 0, 0, 4], dtype=uint8)],
 'd_plus': [array([2, 0, 0, 0], dtype=uint8),
  array([1, 1, 0, 0], dtype=uint8),
  array([1, 0, 1, 0], dtype=uint8),
  array([1, 0, 0, 1], dtype=uint8)],
 'score_h': 12,
 'score_d': 3,
 'score_bust_h': True,
 'score_bust_d': False,
 'win': 0,
 'num_cards_h': 3,
 'num_cards_d': 1,
 'num_residual_cards': 11}

In [7]:
module.evaluate()

0.007792207792207793

In [8]:
module.get_variable(np.array([0,1,0,1]), 
                    np.array([1,0,0,0]), 
                    0)

1

In [9]:
module.optimize_with_gekko()

 ----------------------------------------------------------------
 APMonitor, Version 1.0.3
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  0
   Constants    :  0
   Variables    :  212
   Intermediates:  0
   Connections  :  0
   Equations    :  1
   Residuals    :  1
 
 ________________________________________________
 ss.Eqn(1)
 0 = 0.9922077922077922
 ________________________________________________
 Number of state variables:    212
 Number of total equations: -  0
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    212
 
 **********************************************
 Steady State Optimization with Interior Point Solver
 **********************************************
  
  
 Info: Exact Hessian

******************************************************************************
This program contains 

[0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758985753,
 0.58758